// Block Pool Details API
import { getCollection } from '../lib/mongodb.js';
import { authenticate } from '../lib/auth.js';
import { ObjectId } from 'mongodb';

export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== 'GET') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { id } = req.query;

        if (!id || !ObjectId.isValid(id)) {
            return res.status(400).json({ error: 'Invalid pool ID' });
        }

        const poolsCollection = await getCollection('block_pools');
        const pool = await poolsCollection.findOne({ _id: new ObjectId(id) });

        if (!pool) {
            return res.status(404).json({ error: 'Pool not found' });
        }

        // Build grid representation
        const grid = [];
        for (let row = 0; row < 10; row++) {
            grid[row] = [];
            for (let col = 0; col < 10; col++) {
                const square = (pool.squares || []).find(s => s.row === row && s.col === col);
                grid[row][col] = square ? {
                    owned: true,
                    username: square.username,
                    userId: square.userId?.toString(),
                    isHouse: square.isHouse || false
                } : {
                    owned: false
                };
            }
        }

        // Get user's squares if logged in
        let userSquares = [];
        const user = await authenticate(req);
        if (user) {
            userSquares = (pool.squares || [])
                .filter(s => s.userId && s.userId.toString() === user._id.toString())
                .map(s => ({ row: s.row, col: s.col }));
        }

        // Calculate if user can buy more
        const userSquareCount = userSquares.length;
        const canBuyMore = pool.status === 'open' && userSquareCount < pool.maxPerUser;

        return res.status(200).json({
            success: true,
            pool: {
                _id: pool._id,
                title: pool.title,
                sport: pool.sport,
                homeTeam: pool.homeTeam,
                awayTeam: pool.awayTeam,
                gameTime: pool.gameTime,
                squarePrice: pool.squarePrice,
                maxPerUser: pool.maxPerUser,
                squaresSold: pool.squaresSold || 0,
                prizePool: pool.prizePool || 0,
                status: pool.status,
                numbersAssigned: pool.numbersAssigned,
                rowNumbers: pool.rowNumbers,
                colNumbers: pool.colNumbers,
                payouts: pool.payouts,
                winners: pool.winners || [],
                currentScore: pool.currentScore || { home: 0, away: 0 },
                creatorName: pool.creatorName,
                isAutoGenerated: pool.isAutoGenerated
            },
            grid,
            userSquares,
            userSquareCount,
            canBuyMore,
            availableSquares: 100 - (pool.squaresSold || 0)
        });
    } catch (error) {
        console.error('Pool details error:', error);
        return res.status(500).json({ error: 'Internal server error' });
    }
}
