// Fantasy Contests API - List and Create Contests
import { getCollection } from '../../lib/mongodb.js';
import { authenticate } from '../../lib/auth.js';
import { getTodayET } from '../../lib/timezone.js';
import { fetchGamesByDate } from '../../lib/espn-stats.js';

// Roster positions by sport
const ROSTER_POSITIONS = {
    NFL: [
        { position: 'QB', count: 1 },
        { position: 'RB', count: 2 },
        { position: 'WR', count: 3 },
        { position: 'TE', count: 1 },
        { position: 'FLEX', count: 1, eligible: ['RB', 'WR', 'TE'] },
        { position: 'DEF', count: 1, eligible: ['DEF', 'LB', 'DB', 'DL'] }
    ],
    NBA: [
        { position: 'PG', count: 1 },
        { position: 'SG', count: 1 },
        { position: 'SF', count: 1 },
        { position: 'PF', count: 1 },
        { position: 'C', count: 1 },
        { position: 'UTIL', count: 1, eligible: ['PG', 'SG', 'SF', 'PF', 'C'] }
    ],
    MLB: [
        { position: 'P', count: 2, eligible: ['SP', 'RP'] },
        { position: 'C', count: 1 },
        { position: '1B', count: 1 },
        { position: '2B', count: 1 },
        { position: '3B', count: 1 },
        { position: 'SS', count: 1 },
        { position: 'OF', count: 3 }
    ],
    NHL: [
        { position: 'C', count: 2 },
        { position: 'W', count: 3, eligible: ['LW', 'RW'] },
        { position: 'D', count: 2 },
        { position: 'G', count: 1 },
        { position: 'UTIL', count: 1, eligible: ['C', 'LW', 'RW', 'D'] }
    ]
};

export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    const contestsCollection = await getCollection('fantasy_contests');

    // GET - List contests
    if (req.method === 'GET') {
        try {
            const { sport, status, limit = 20, includeUserEntries } = req.query;

            const query = {};
            if (sport) query.sport = sport;
            if (status) {
                query.status = status;
            } else {
                // Default to upcoming and live contests
                query.status = { $in: ['upcoming', 'live'] };
            }

            const contests = await contestsCollection
                .find(query)
                .sort({ gameDate: 1, createdAt: -1 })
                .limit(parseInt(limit))
                .toArray();

            // If user is logged in and wants their entries
            let userEntries = {};
            if (includeUserEntries === 'true') {
                const user = await authenticate(req);
                if (user) {
                    const entriesCollection = await getCollection('fantasy_entries');
                    const entries = await entriesCollection.find({
                        userId: user._id,
                        contestId: { $in: contests.map(c => c._id) }
                    }).toArray();

                    entries.forEach(e => {
                        userEntries[e.contestId.toString()] = e;
                    });
                }
            }

            return res.status(200).json({
                success: true,
                contests: contests.map(c => ({
                    ...c,
                    // Calculate prize pool dynamically: entryFee × entryCount
                    prizePool: (c.entryFee || 0) * (c.entryCount || 0),
                    userEntry: userEntries[c._id.toString()] || null
                }))
            });
        } catch (error) {
            console.error('List contests error:', error);
            return res.status(500).json({ error: 'Internal server error' });
        }
    }

    // POST - Create contest (admin only or auto-generation)
    if (req.method === 'POST') {
        try {
            const { sport, date, entryFee = 0, title, isAutoGenerated } = req.body;

            // Validate sport
            if (!sport || !['NFL', 'NBA', 'MLB', 'NHL'].includes(sport)) {
                return res.status(400).json({ error: 'Invalid sport' });
            }

            // Get games for the date from ESPN
            const targetDate = date || getTodayET();
            const gamesData = await fetchGamesByDate(sport, targetDate);

            if (!gamesData || gamesData.length === 0) {
                return res.status(400).json({ error: `No ${sport} games found for ${targetDate}` });
            }

            // Extract game IDs and times
            const gameIds = gamesData.map(g => g.id);
            const now = new Date();
            const gameTimes = gamesData
                .map(g => g.gameTime ? new Date(g.gameTime) : null)
                .filter(d => d && !isNaN(d.getTime()))
                .sort((a, b) => a - b);

            // For locksAt, prefer the earliest future game time
            const futureGameTimes = gameTimes.filter(d => d > now);
            const earliestGame = futureGameTimes[0] || gameTimes[0] || new Date(targetDate + 'T19:00:00-05:00');
            const latestGame = gameTimes[gameTimes.length - 1] || earliestGame;

            // If all games have started, give at least 15 min to enter
            const minLockTime = new Date(now.getTime() + 15 * 60 * 1000);
            const locksAt = earliestGame > now ? earliestGame : minLockTime;

            // Generate title if not provided
            const fee = parseInt(entryFee) || 0;
            const contestTitle = title || `${sport} ${targetDate} - ${fee === 0 ? 'Free' : `${fee} DD`} Contest`;

            const contest = {
                sport,
                title: contestTitle,
                gameDate: new Date(targetDate + 'T12:00:00-05:00'),
                gameDateString: targetDate,
                gameIds,
                salaryCap: 45000,
                rosterPositions: ROSTER_POSITIONS[sport],
                entryFee: fee,
                maxEntries: 3,
                maxTotalEntries: 1000,
                status: 'upcoming',
                entryCount: 0,
                createdAt: new Date(),
                locksAt,
                endsAt: latestGame,
                isAutoGenerated: isAutoGenerated || false
            };

            const result = await contestsCollection.insertOne(contest);

            return res.status(201).json({
                success: true,
                contest: {
                    _id: result.insertedId,
                    ...contest
                }
            });
        } catch (error) {
            console.error('Create contest error:', error);
            return res.status(500).json({ error: 'Internal server error' });
        }
    }

    return res.status(405).json({ error: 'Method not allowed' });
}
